#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Abyss_Behavior_PrimaryFire_Mutator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Abyss_Behavior_PrimaryFire_Mutator.BP_Abyss_Behavior_PrimaryFire_Mutator_C
// 0x0008 (0x0118 - 0x0110)
class UBP_Abyss_Behavior_PrimaryFire_Mutator_C final : public URGCharBehaviorMutatorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0110(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AttachBreach(class ARPawnBase* Pawn);
	void ExecuteUbergraph_BP_Abyss_Behavior_PrimaryFire_Mutator(int32 EntryPoint);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void MutatorRankChanged(int32 NewRank, class URMutatorPrimaryAsset* MutatorPrimaryAsset);
	void RunBehaviour(const class AActor* TriggeringActor);
	void RunPrimaryFireBehavior(float HealthDamage, class AActor* TriggeringActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Abyss_Behavior_PrimaryFire_Mutator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Abyss_Behavior_PrimaryFire_Mutator_C")
	}
	static class UBP_Abyss_Behavior_PrimaryFire_Mutator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Abyss_Behavior_PrimaryFire_Mutator_C>();
	}
};
DUMPER7_ASSERTS_UBP_Abyss_Behavior_PrimaryFire_Mutator_C;

}

