#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArrowProjectile_Pierce_Script

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_structs.hpp"
#include "BP_ArrowProjectile_Script_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ArrowProjectile_Pierce_Script.BP_ArrowProjectile_Pierce_Script_C
// 0x0150 (0x0268 - 0x0118)
class UBP_ArrowProjectile_Pierce_Script_C final : public UBP_ArrowProjectile_Script_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ArrowProjectile_Pierce_Script_C; // 0x0118(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        DamageMultiplierPerPierce;                         // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRMutableFloat                         Base_Damage;                                       // 0x0128(0x0128)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        EnemiesPierced;                                    // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WasSweetspot;                                      // 0x0258(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        SweetspotBonus;                                    // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ArrowProjectile_Pierce_Script(int32 EntryPoint);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void OnProjectilePierce(class ARProjectileBase* Projectile);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ArrowProjectile_Pierce_Script_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ArrowProjectile_Pierce_Script_C")
	}
	static class UBP_ArrowProjectile_Pierce_Script_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ArrowProjectile_Pierce_Script_C>();
	}
};
DUMPER7_ASSERTS_UBP_ArrowProjectile_Pierce_Script_C;

}

