#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BowAccuracy_Challenge

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BowAccuracy_Challenge.BP_BowAccuracy_Challenge_C
// 0x0008 (0x0038 - 0x0030)
class UBP_BowAccuracy_Challenge_C final : public URChallengeScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_BowAccuracy_Challenge(int32 EntryPoint);
	void OnApplicableRunStarted();
	void OnDealtDamage(class ARPawnBase* Pawn, const struct FDamageCombatEvent& DamageEventData);
	void OnFinishRun(bool RunFailed);
	void OnProjectileHit(class ARPlayerPawn* Player, class AActor* HitActor, class ARProjectileBase* ProjectileActor);
	void ResetChallenge();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BowAccuracy_Challenge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BowAccuracy_Challenge_C")
	}
	static class UBP_BowAccuracy_Challenge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BowAccuracy_Challenge_C>();
	}
};
DUMPER7_ASSERTS_UBP_BowAccuracy_Challenge_C;

}

