#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CombatBow_Body

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CombatBow_Body.BP_CombatBow_Body_C
// 0x0058 (0x03E8 - 0x0390)
class ABP_CombatBow_Body_C final : public ARWeapon
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URSkeletalMeshComponent*                Primary_Skeletal_Mesh_Component;                   // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URNS_Combatbow_Arrow_Attached_01_C*     RNS_Combatbow_Arrow_Attached_01;                   // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   AnimatedLight;                                     // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       DynamicMaterials;                                  // 0x03B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         TargetLightIntensity;                              // 0x03C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C4[0x4];                                      // 0x03C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               ArrowDynamicMaterial;                              // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBP_BowBase_ModScript_C*                ActiveModscript;                                   // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        CutoutSpeed;                                       // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetCutout;                                      // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CombatBow_Body(int32 EntryPoint);
	TArray<struct FTransform> GetMuzzleTransforms();
	void GetOrCreateDynamicMaterial(int32 ElementIndex, class UMaterialInstanceDynamic** DynamicMaterial);
	void GetTargetCutoutAmount(double TargetAmount, double DeltaTime, double* Result);
	void PlayFullyChargedFX(double SweetSpotTImeMin, double SweetSpotTimeMax);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void RefreshMaterialInstances();
	void UpdateBowstringFX(float CutoutAmount);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CombatBow_Body_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CombatBow_Body_C")
	}
	static class ABP_CombatBow_Body_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CombatBow_Body_C>();
	}
};
DUMPER7_ASSERTS_ABP_CombatBow_Body_C;

}

