#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DiscThrower_SearchAndDestroy_Modscript

#include "Basic.hpp"

#include "BP_DiscThrower_SearchAndDestroy_Modscript_classes.hpp"
#include "BP_DiscThrower_SearchAndDestroy_Modscript_parameters.hpp"


namespace SDK
{

// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.ExecuteUbergraph_BP_DiscThrower_SearchAndDestroy_Modscript
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::ExecuteUbergraph_BP_DiscThrower_SearchAndDestroy_Modscript(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "ExecuteUbergraph_BP_DiscThrower_SearchAndDestroy_Modscript");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_ExecuteUbergraph_BP_DiscThrower_SearchAndDestroy_Modscript Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.FilterInvulnerableTargets
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AActor*>&                  Enemies                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<class AActor*>*                  FilteredEnemies                                        (Parm, OutParm)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::FilterInvulnerableTargets(TArray<class AActor*>& Enemies, TArray<class AActor*>* FilteredEnemies)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "FilterInvulnerableTargets");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_FilterInvulnerableTargets Parms{};

	Parms.Enemies = std::move(Enemies);

	UObject::ProcessEvent(Func, &Parms);

	Enemies = std::move(Parms.Enemies);

	if (FilteredEnemies != nullptr)
		*FilteredEnemies = std::move(Parms.FilteredEnemies);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.Fire
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::Fire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "Fire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.GetTargettingLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ARProjectileBase*                 Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::GetTargettingLocation(class AActor* Target, class ARProjectileBase* Projectile, struct FVector* Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "GetTargettingLocation");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_GetTargettingLocation Parms{};

	Parms.Target = Target;
	Parms.Projectile = Projectile;

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.IsAnyDiscVisible
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::IsAnyDiscVisible(bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "IsAnyDiscVisible");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_IsAnyDiscVisible Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.K2_TickScript
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::K2_TickScript(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "K2_TickScript");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_K2_TickScript Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.OnProjectileHit
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARPlayerPawn*                     Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           HitActor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ARProjectileBase*                 ProjectileActor                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::OnProjectileHit(class ARPlayerPawn* Player, class AActor* HitActor, class ARProjectileBase* ProjectileActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "OnProjectileHit");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_OnProjectileHit Parms{};

	Parms.Player = Player;
	Parms.HitActor = HitActor;
	Parms.ProjectileActor = ProjectileActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.PlayTargetFoundFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARProjectileBase*                 Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::PlayTargetFoundFX(class ARProjectileBase* Projectile, class AActor* TargetActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "PlayTargetFoundFX");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_PlayTargetFoundFX Parms{};

	Parms.Projectile = Projectile;
	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.PreFire
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::PreFire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "PreFire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_DiscThrower_SearchAndDestroy_Modscript.BP_DiscThrower_SearchAndDestroy_Modscript_C.SetNewTarget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARProjectileBase*                 Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           NewTarget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_DiscThrower_SearchAndDestroy_Modscript_C::SetNewTarget(class ARProjectileBase* Projectile, class AActor* NewTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DiscThrower_SearchAndDestroy_Modscript_C", "SetNewTarget");

	Params::BP_DiscThrower_SearchAndDestroy_Modscript_C_SetNewTarget Parms{};

	Parms.Projectile = Projectile;
	Parms.NewTarget = NewTarget;

	UObject::ProcessEvent(Func, &Parms);
}

}

