#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DropShield_Slow_StatusEffect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DropShield_Slow_StatusEffect.BP_DropShield_Slow_StatusEffect_C
// 0x0008 (0x04E8 - 0x04E0)
class UBP_DropShield_Slow_StatusEffect_C final : public URStatusEffectGScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_DropShield_Slow_StatusEffect(int32 EntryPoint);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void OnStacksUpdated(int32 ShieldAmount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DropShield_Slow_StatusEffect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DropShield_Slow_StatusEffect_C")
	}
	static class UBP_DropShield_Slow_StatusEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DropShield_Slow_StatusEffect_C>();
	}
};
DUMPER7_ASSERTS_UBP_DropShield_Slow_StatusEffect_C;

}

