#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DominoBomb_CharacterMutator

#include "Basic.hpp"

#include "BP_AddProjectileEffectToFragGrenade_CharacterMutator_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DominoBomb_CharacterMutator.BP_DominoBomb_CharacterMutator_C
// 0x0010 (0x0128 - 0x0118)
class UBP_DominoBomb_CharacterMutator_C final : public UBP_AddProjectileEffectToFragGrenade_CharacterMutator_C
{
public:
	double                                        MinExplosionDelay;                                 // 0x0118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxExplosionDelay;                                 // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetDamage(double* DamageIncreasePercent);
	class FText GetMutatorDescription();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DominoBomb_CharacterMutator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DominoBomb_CharacterMutator_C")
	}
	static class UBP_DominoBomb_CharacterMutator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DominoBomb_CharacterMutator_C>();
	}
};
DUMPER7_ASSERTS_UBP_DominoBomb_CharacterMutator_C;

}

