#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DiscGun_Dynamo_CosmeticsScript

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DiscGun_Dynamo_CosmeticsScript.BP_DiscGun_Dynamo_CosmeticsScript_C
// 0x0020 (0x0100 - 0x00E0)
class UBP_DiscGun_Dynamo_CosmeticsScript_C : public URGWeaponCosmeticScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UStaticMeshComponent*>           AttachedStaticMeshes;                              // 0x00E8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class URWeaponModPrimaryAsset*                WeaponModRef;                                      // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DiscGun_Dynamo_CosmeticsScript(int32 EntryPoint);
	void HideDisksDelayed();
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void OnAmmoUpdated_Event(class ARPlayerPawn* Player, class URGScript* SourceScript, int32 Ammo, int32 Delta);
	void OnFinish_0996257842ADB356E126F2A62FE574F6();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DiscGun_Dynamo_CosmeticsScript_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DiscGun_Dynamo_CosmeticsScript_C")
	}
	static class UBP_DiscGun_Dynamo_CosmeticsScript_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DiscGun_Dynamo_CosmeticsScript_C>();
	}
};
DUMPER7_ASSERTS_UBP_DiscGun_Dynamo_CosmeticsScript_C;

}

