#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DiscThrowerDynamo_Projectile

#include "Basic.hpp"

#include "BP_DiscThrower_Projectile_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DiscThrowerDynamo_Projectile.BP_DiscThrowerDynamo_Projectile_C
// 0x0000 (0x0658 - 0x0658)
class ABP_DiscThrowerDynamo_Projectile_C final : public ABP_DiscThrower_Projectile_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DiscThrowerDynamo_Projectile_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DiscThrowerDynamo_Projectile_C")
	}
	static class ABP_DiscThrowerDynamo_Projectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DiscThrowerDynamo_Projectile_C>();
	}
};
DUMPER7_ASSERTS_ABP_DiscThrowerDynamo_Projectile_C;

}

