#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DefaultExplosion_Grenade

#include "Basic.hpp"

#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DefaultExplosion_Grenade.BP_DefaultExplosion_Grenade_C
// 0x0000 (0x06F8 - 0x06F8)
class ABP_DefaultExplosion_Grenade_C : public ARGrenade
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DefaultExplosion_Grenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DefaultExplosion_Grenade_C")
	}
	static class ABP_DefaultExplosion_Grenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DefaultExplosion_Grenade_C>();
	}
};
DUMPER7_ASSERTS_ABP_DefaultExplosion_Grenade_C;

}

