#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HealthBonus_CharacterMutator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HealthBonus_CharacterMutator.BP_HealthBonus_CharacterMutator_C
// 0x0020 (0x0128 - 0x0108)
class UBP_HealthBonus_CharacterMutator_C final : public URGCharacterMutatorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0108(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        BonusHPIncrease;                                   // 0x0110(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         InternalRank;                                      // 0x0118(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   MutableFloatKey;                                   // 0x011C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddHealthBonus();
	void ExecuteUbergraph_BP_HealthBonus_CharacterMutator(int32 EntryPoint);
	void IsPlayerStateValid(bool* RetValue);
	void K2_ActivateScript();
	void K2_DeactivateScript();
	void OnInvoke_C6B33D444EAF89A492066B957C25494F();
	void OnReconnectDoneServer(const struct FRDisconnectedPlayerData& PlayerData);
	void SetNewRank(int32 NewRank);

	class FText GetDescription() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HealthBonus_CharacterMutator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HealthBonus_CharacterMutator_C")
	}
	static class UBP_HealthBonus_CharacterMutator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HealthBonus_CharacterMutator_C>();
	}
};
DUMPER7_ASSERTS_UBP_HealthBonus_CharacterMutator_C;

}

