#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Headstart_StatusEffect

#include "Basic.hpp"

#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Headstart_StatusEffect.BP_Headstart_StatusEffect_C
// 0x0000 (0x04E0 - 0x04E0)
class UBP_Headstart_StatusEffect_C final : public URStatusEffectGScript
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Headstart_StatusEffect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Headstart_StatusEffect_C")
	}
	static class UBP_Headstart_StatusEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Headstart_StatusEffect_C>();
	}
};
DUMPER7_ASSERTS_UBP_Headstart_StatusEffect_C;

}

