#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lobby_FishDeity_Secret_Door

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.CanInteract
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_CanInteract final
{
public:
	class APlayerController*                      Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_CanInteract;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.ExecuteUbergraph_BP_Lobby_FishDeity_Secret_Door
// 0x0178 (0x0178 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_ExecuteUbergraph_BP_Lobby_FishDeity_Secret_Door final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VLerp_ReturnValue;                        // 0x0010(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class APlayerController*                K2Node_Event_PlayerController;                     // 0x0028(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_InteractingActor;                     // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_NewVisible;                           // 0x0038(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      K2Node_Event_controller_2;                         // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0048(0x0100)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_Event_controller_1;                         // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARChallengeManager*                     CallFunc_GetChallengeManager_ReturnValue;          // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_Event_controller;                           // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChallengeCompleted_ReturnValue;         // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChallengeCompleted_ReturnValue_1;       // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsChallengeCompleted_ReturnValue_2;       // 0x016A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x016B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x016C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16D[0x3];                                      // 0x016D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_SetPlayRate_NewRate_ImplicitCast;         // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_ExecuteUbergraph_BP_Lobby_FishDeity_Secret_Door;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.IsShareable
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_IsShareable final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_IsShareable;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.OnFocus
// 0x0008 (0x0008 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_OnFocus final
{
public:
	class APlayerController*                      Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_OnFocus;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.OnFocusGone
// 0x0008 (0x0008 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_OnFocusGone final
{
public:
	class APlayerController*                      Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_OnFocusGone;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.OnInteract
// 0x0008 (0x0008 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_OnInteract final
{
public:
	class APlayerController*                      Controller;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_OnInteract;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.ShareInteractableActor
// 0x0008 (0x0008 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_ShareInteractableActor final
{
public:
	const class APlayerController*                PlayerController;                                  // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_ShareInteractableActor;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.ToggleInteractionIndicatorVisibility
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_ToggleInteractionIndicatorVisibility final
{
public:
	class AActor*                                 InteractingActor;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          NewVisible;                                        // 0x0008(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_ToggleInteractionIndicatorVisibility;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableAlternativeDescription
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableAlternativeDescription final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableAlternativeDescription;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableCost
// 0x0004 (0x0004 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableCost final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableCost;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableCostCurrencyType
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableCostCurrencyType final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableCostCurrencyType;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableDescription
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableDescription final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableDescription;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableName
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableName final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableName;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractableSubHeader
// 0x0010 (0x0010 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractableSubHeader final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractableSubHeader;

// Function BP_Lobby_FishDeity_Secret_Door.BP_Lobby_FishDeity_Secret_Door_C.GetInteractionIndicatorWidget
// 0x0008 (0x0008 - 0x0000)
struct BP_Lobby_FishDeity_Secret_Door_C_GetInteractionIndicatorWidget final
{
public:
	class UWidgetComponent*                       ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Lobby_FishDeity_Secret_Door_C_GetInteractionIndicatorWidget;

}

