#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OceanGod_Tentacle_Stun_ProjectileScript

#include "Basic.hpp"

#include "BP_OceanGod_Tentacle_Stun_ProjectileScript_classes.hpp"
#include "BP_OceanGod_Tentacle_Stun_ProjectileScript_parameters.hpp"


namespace SDK
{

// Function BP_OceanGod_Tentacle_Stun_ProjectileScript.BP_OceanGod_Tentacle_Stun_ProjectileScript_C.ExecuteUbergraph_BP_OceanGod_Tentacle_Stun_ProjectileScript
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_OceanGod_Tentacle_Stun_ProjectileScript_C::ExecuteUbergraph_BP_OceanGod_Tentacle_Stun_ProjectileScript(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanGod_Tentacle_Stun_ProjectileScript_C", "ExecuteUbergraph_BP_OceanGod_Tentacle_Stun_ProjectileScript");

	Params::BP_OceanGod_Tentacle_Stun_ProjectileScript_C_ExecuteUbergraph_BP_OceanGod_Tentacle_Stun_ProjectileScript Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_OceanGod_Tentacle_Stun_ProjectileScript.BP_OceanGod_Tentacle_Stun_ProjectileScript_C.K2_OnHit
// (Event, Public, BlueprintEvent)

void UBP_OceanGod_Tentacle_Stun_ProjectileScript_C::K2_OnHit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanGod_Tentacle_Stun_ProjectileScript_C", "K2_OnHit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_OceanGod_Tentacle_Stun_ProjectileScript.BP_OceanGod_Tentacle_Stun_ProjectileScript_C.OnEffectSpawned_E89FCC644E940612A3DED9AB95DFE178
// (BlueprintCallable, BlueprintEvent)

void UBP_OceanGod_Tentacle_Stun_ProjectileScript_C::OnEffectSpawned_E89FCC644E940612A3DED9AB95DFE178()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanGod_Tentacle_Stun_ProjectileScript_C", "OnEffectSpawned_E89FCC644E940612A3DED9AB95DFE178");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_OceanGod_Tentacle_Stun_ProjectileScript.BP_OceanGod_Tentacle_Stun_ProjectileScript_C.OnFailed_E89FCC644E940612A3DED9AB95DFE178
// (BlueprintCallable, BlueprintEvent)

void UBP_OceanGod_Tentacle_Stun_ProjectileScript_C::OnFailed_E89FCC644E940612A3DED9AB95DFE178()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanGod_Tentacle_Stun_ProjectileScript_C", "OnFailed_E89FCC644E940612A3DED9AB95DFE178");

	UObject::ProcessEvent(Func, nullptr);
}

}

