#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickupable_Syringe

#include "Basic.hpp"

#include "BP_Pickupable_Syringe_classes.hpp"
#include "BP_Pickupable_Syringe_parameters.hpp"


namespace SDK
{

// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.CanInteract
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Pickupable_Syringe_C::CanInteract(class APlayerController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "CanInteract");

	Params::BP_Pickupable_Syringe_C_CanInteract Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.ExecuteUbergraph_BP_Pickupable_Syringe
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickupable_Syringe_C::ExecuteUbergraph_BP_Pickupable_Syringe(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "ExecuteUbergraph_BP_Pickupable_Syringe");

	Params::BP_Pickupable_Syringe_C_ExecuteUbergraph_BP_Pickupable_Syringe Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.IdleAnimationTick
// (BlueprintCallable, BlueprintEvent)

void ABP_Pickupable_Syringe_C::IdleAnimationTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "IdleAnimationTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.OnInteract
// (Event, Public, BlueprintEvent)
// Parameters:
// class APlayerController*                Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Pickupable_Syringe_C::OnInteract(class APlayerController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "OnInteract");

	Params::BP_Pickupable_Syringe_C_OnInteract Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Pickupable_Syringe_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.StartIdleAnimation
// (BlueprintCallable, BlueprintEvent)

void ABP_Pickupable_Syringe_C::StartIdleAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "StartIdleAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.TriggerPickup
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Pickupable_Syringe_C::TriggerPickup(class APlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "TriggerPickup");

	Params::BP_Pickupable_Syringe_C_TriggerPickup Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickupable_Syringe.BP_Pickupable_Syringe_C.GetInteractableCost
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 ABP_Pickupable_Syringe_C::GetInteractableCost() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pickupable_Syringe_C", "GetInteractableCost");

	Params::BP_Pickupable_Syringe_C_GetInteractableCost Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

