#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScatterBase_ModScript

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Base_ModScript_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ScatterBase_ModScript.BP_ScatterBase_ModScript_C
// 0x0010 (0x0160 - 0x0150)
class UBP_ScatterBase_ModScript_C : public UBP_Base_ModScript_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ScatterBase_ModScript_C;         // 0x0150(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         ProjectileCount;                                   // 0x0158(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ScatterBase_ModScript(int32 EntryPoint);
	void Fire();
	void OnAmmoUpdated_8A2D37364D98750908849EB64C0002AB();
	void OnFail_8A2D37364D98750908849EB64C0002AB();

	class FText GetDescription() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ScatterBase_ModScript_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ScatterBase_ModScript_C")
	}
	static class UBP_ScatterBase_ModScript_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ScatterBase_ModScript_C>();
	}
};
DUMPER7_ASSERTS_UBP_ScatterBase_ModScript_C;

}

