#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillTree_UpgradedInventions_CharacterMutator

#include "Basic.hpp"

#include "BP_SkillTree_UpgradedInventions_CharacterMutator_classes.hpp"
#include "BP_SkillTree_UpgradedInventions_CharacterMutator_parameters.hpp"


namespace SDK
{

// Function BP_SkillTree_UpgradedInventions_CharacterMutator.BP_SkillTree_UpgradedInventions_CharacterMutator_C.ExecuteUbergraph_BP_SkillTree_UpgradedInventions_CharacterMutator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SkillTree_UpgradedInventions_CharacterMutator_C::ExecuteUbergraph_BP_SkillTree_UpgradedInventions_CharacterMutator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillTree_UpgradedInventions_CharacterMutator_C", "ExecuteUbergraph_BP_SkillTree_UpgradedInventions_CharacterMutator");

	Params::BP_SkillTree_UpgradedInventions_CharacterMutator_C_ExecuteUbergraph_BP_SkillTree_UpgradedInventions_CharacterMutator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillTree_UpgradedInventions_CharacterMutator.BP_SkillTree_UpgradedInventions_CharacterMutator_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_SkillTree_UpgradedInventions_CharacterMutator_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillTree_UpgradedInventions_CharacterMutator_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkillTree_UpgradedInventions_CharacterMutator.BP_SkillTree_UpgradedInventions_CharacterMutator_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_SkillTree_UpgradedInventions_CharacterMutator_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillTree_UpgradedInventions_CharacterMutator_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SkillTree_UpgradedInventions_CharacterMutator.BP_SkillTree_UpgradedInventions_CharacterMutator_C.OnActivatableAbilityChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class URPlayerGScriptComponent*         Owner                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class URGCharacterMutatorScript*        AbilityScript                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_SkillTree_UpgradedInventions_CharacterMutator_C::OnActivatableAbilityChanged(class URPlayerGScriptComponent* Owner, class URGCharacterMutatorScript* AbilityScript)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillTree_UpgradedInventions_CharacterMutator_C", "OnActivatableAbilityChanged");

	Params::BP_SkillTree_UpgradedInventions_CharacterMutator_C_OnActivatableAbilityChanged Parms{};

	Parms.Owner = Owner;
	Parms.AbilityScript = AbilityScript;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SkillTree_UpgradedInventions_CharacterMutator.BP_SkillTree_UpgradedInventions_CharacterMutator_C.RefreshSkillTreeMutator
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const int32                             MutatorRank                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SkillTree_UpgradedInventions_CharacterMutator_C::RefreshSkillTreeMutator(const int32 MutatorRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SkillTree_UpgradedInventions_CharacterMutator_C", "RefreshSkillTreeMutator");

	Params::BP_SkillTree_UpgradedInventions_CharacterMutator_C_RefreshSkillTreeMutator Parms{};

	Parms.MutatorRank = MutatorRank;

	UObject::ProcessEvent(Func, &Parms);
}

}

