#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shotgun_AutomaticAction_WeaponMutator

#include "Basic.hpp"

#include "BP_Shotgun_AutomaticAction_WeaponMutator_classes.hpp"
#include "BP_Shotgun_AutomaticAction_WeaponMutator_parameters.hpp"


namespace SDK
{

// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.ExecuteUbergraph_BP_Shotgun_AutomaticAction_WeaponMutator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::ExecuteUbergraph_BP_Shotgun_AutomaticAction_WeaponMutator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "ExecuteUbergraph_BP_Shotgun_AutomaticAction_WeaponMutator");

	Params::BP_Shotgun_AutomaticAction_WeaponMutator_C_ExecuteUbergraph_BP_Shotgun_AutomaticAction_WeaponMutator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.OnCancelled_AF90247142EE4A699A3FD380A445F552
// (BlueprintCallable, BlueprintEvent)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::OnCancelled_AF90247142EE4A699A3FD380A445F552()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "OnCancelled_AF90247142EE4A699A3FD380A445F552");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.OnFinish_AF90247142EE4A699A3FD380A445F552
// (BlueprintCallable, BlueprintEvent)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::OnFinish_AF90247142EE4A699A3FD380A445F552()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "OnFinish_AF90247142EE4A699A3FD380A445F552");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Shotgun_AutomaticAction_WeaponMutator.BP_Shotgun_AutomaticAction_WeaponMutator_C.OnPostFire
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsPrimaryMod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Shotgun_AutomaticAction_WeaponMutator_C::OnPostFire(bool IsPrimaryMod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Shotgun_AutomaticAction_WeaponMutator_C", "OnPostFire");

	Params::BP_Shotgun_AutomaticAction_WeaponMutator_C_OnPostFire Parms{};

	Parms.IsPrimaryMod = IsPrimaryMod;

	UObject::ProcessEvent(Func, &Parms);
}

}

