#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TimeWarp_CharacterMutator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_structs.hpp"
#include "RGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TimeWarp_CharacterMutator.BP_TimeWarp_CharacterMutator_C
// 0x0018 (0x0120 - 0x0108)
class UBP_TimeWarp_CharacterMutator_C final : public URGCharacterMutatorScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0108(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         AreaEffectSizeMultiplier;                          // 0x0110(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_114[0x4];                                      // 0x0114(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        EstimatedAreaEffectBaseRadius;                     // 0x0118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_TimeWarp_CharacterMutator(int32 EntryPoint);
	class FText GetMutatorDescription();
	void K2_ActivateScript();
	void OnActorEnterProximity(class AActor* Actor);
	void OnActorExitProximity(class AActor* Actor);
	void OnAreaEffectSizeUpdated(double NewSizeMultiplier);
	void OnDestroyed(class AActor* DestroyedActor);
	void OnGroundEffectSpawned(class ARAreaEffect* GroundEffect);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TimeWarp_CharacterMutator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TimeWarp_CharacterMutator_C")
	}
	static class UBP_TimeWarp_CharacterMutator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TimeWarp_CharacterMutator_C>();
	}
};
DUMPER7_ASSERTS_UBP_TimeWarp_CharacterMutator_C;

}

