#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeslaRifle_UnstableCoil_ModScript

#include "Basic.hpp"

#include "BP_TeslaRifle_UnstableCoil_ModScript_classes.hpp"
#include "BP_TeslaRifle_UnstableCoil_ModScript_parameters.hpp"


namespace SDK
{

// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.CheckTargetAmount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::CheckTargetAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "CheckTargetAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.ExecuteUbergraph_BP_TeslaRifle_UnstableCoil_ModScript
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::ExecuteUbergraph_BP_TeslaRifle_UnstableCoil_ModScript(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "ExecuteUbergraph_BP_TeslaRifle_UnstableCoil_ModScript");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_ExecuteUbergraph_BP_TeslaRifle_UnstableCoil_ModScript Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.FanFire
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  RotationOffset                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::FanFire(const struct FRotator& RotationOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "FanFire");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_FanFire Parms{};

	Parms.RotationOffset = std::move(RotationOffset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.FinishFire
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::FinishFire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "FinishFire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.Fire
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::Fire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "Fire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.GetEmptyIndexes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBPS_Tesla_UnstableCoil_Target>*EmptyIndexes                                           (Parm, OutParm)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::GetEmptyIndexes(TArray<struct FBPS_Tesla_UnstableCoil_Target>* EmptyIndexes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "GetEmptyIndexes");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_GetEmptyIndexes Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EmptyIndexes != nullptr)
		*EmptyIndexes = std::move(Parms.EmptyIndexes);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.InitializeVFX
// (BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::InitializeVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "InitializeVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.K2_ActivateScript
// (Event, Public, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::K2_ActivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "K2_ActivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.K2_DeactivateScript
// (Event, Public, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::K2_DeactivateScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "K2_DeactivateScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.K2_OnBeginFire
// (Event, Public, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::K2_OnBeginFire()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "K2_OnBeginFire");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.K2_TickScript
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::K2_TickScript(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "K2_TickScript");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_K2_TickScript Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.OnAmmoUpdated_885E18C443AB08BE939DB2AC62150133
// (BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::OnAmmoUpdated_885E18C443AB08BE939DB2AC62150133()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "OnAmmoUpdated_885E18C443AB08BE939DB2AC62150133");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.OnBeat
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ClockName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EQuartzCommandQuantization              QuantizationType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NumBars                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Beat                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   BeatFraction                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::OnBeat(class FName ClockName, EQuartzCommandQuantization QuantizationType, int32 NumBars, int32 Beat, float BeatFraction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "OnBeat");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_OnBeat Parms{};

	Parms.ClockName = ClockName;
	Parms.QuantizationType = QuantizationType;
	Parms.NumBars = NumBars;
	Parms.Beat = Beat;
	Parms.BeatFraction = BeatFraction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.OnFail_885E18C443AB08BE939DB2AC62150133
// (BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::OnFail_885E18C443AB08BE939DB2AC62150133()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "OnFail_885E18C443AB08BE939DB2AC62150133");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.OnFail_CA319BC1449EB2BB84E03C9E36826EE2
// (BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::OnFail_CA319BC1449EB2BB84E03C9E36826EE2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "OnFail_CA319BC1449EB2BB84E03C9E36826EE2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.OnProjectileSpawned_CA319BC1449EB2BB84E03C9E36826EE2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARProjectileBase*                 Projectile                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::OnProjectileSpawned_CA319BC1449EB2BB84E03C9E36826EE2(class ARProjectileBase* Projectile)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "OnProjectileSpawned_CA319BC1449EB2BB84E03C9E36826EE2");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_OnProjectileSpawned_CA319BC1449EB2BB84E03C9E36826EE2 Parms{};

	Parms.Projectile = Projectile;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.SetTargetValuesAtIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   TargetLocation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   CurrentRandomDeviation                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::SetTargetValuesAtIndex(int32 Index_0, const struct FVector& TargetLocation, class AActor* TargetActor, const struct FVector& CurrentRandomDeviation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "SetTargetValuesAtIndex");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_SetTargetValuesAtIndex Parms{};

	Parms.Index_0 = Index_0;
	Parms.TargetLocation = std::move(TargetLocation);
	Parms.TargetActor = TargetActor;
	Parms.CurrentRandomDeviation = std::move(CurrentRandomDeviation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.SpawnWeaponFireFX
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class URNiagaraComponent>   RNiagaraComponent                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::SpawnWeaponFireFX(TSubclassOf<class URNiagaraComponent> RNiagaraComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "SpawnWeaponFireFX");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_SpawnWeaponFireFX Parms{};

	Parms.RNiagaraComponent = RNiagaraComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.SpawnWeaponFireSFX
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundBase*                       SoundTemplate                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::SpawnWeaponFireSFX(class USoundBase* SoundTemplate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "SpawnWeaponFireSFX");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_SpawnWeaponFireSFX Parms{};

	Parms.SoundTemplate = SoundTemplate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.TargetsContainsActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   HasTarget                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::TargetsContainsActor(class UObject* TargetActor, bool* HasTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "TargetsContainsActor");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_TargetsContainsActor Parms{};

	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);

	if (HasTarget != nullptr)
		*HasTarget = Parms.HasTarget;
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.ToggleBeamVFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Active                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::ToggleBeamVFX(bool Active)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "ToggleBeamVFX");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_ToggleBeamVFX Parms{};

	Parms.Active = Active;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.UpdateBeamVFX
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::UpdateBeamVFX(const struct FVector& Location, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "UpdateBeamVFX");

	Params::BP_TeslaRifle_UnstableCoil_ModScript_C_UpdateBeamVFX Parms{};

	Parms.Location = std::move(Location);
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TeslaRifle_UnstableCoil_ModScript.BP_TeslaRifle_UnstableCoil_ModScript_C.ValidateCurrentTargets
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_TeslaRifle_UnstableCoil_ModScript_C::ValidateCurrentTargets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeslaRifle_UnstableCoil_ModScript_C", "ValidateCurrentTargets");

	UObject::ProcessEvent(Func, nullptr);
}

}

