#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TutorialEncounter_ObjectiveScript

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_TutorialEncounter_ObjectiveScript.BP_TutorialEncounter_ObjectiveScript_C.GetProgressionText
// 0x0010 (0x0010 - 0x0000)
struct BP_TutorialEncounter_ObjectiveScript_C_GetProgressionText final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BP_TutorialEncounter_ObjectiveScript_C_GetProgressionText;

}

