#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS_Tesla_UnstableCoil_Target

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct BPS_Tesla_UnstableCoil_Target.BPS_Tesla_UnstableCoil_Target
// 0x0040 (0x0040 - 0x0000)
struct FBPS_Tesla_UnstableCoil_Target final
{
public:
	class AActor*                                 TargetActor_2_EB8D3B394EB144F69AC677AACE0C8D01;    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	struct FVector                                TargetLocation_8_51E312AF44535FB1BD30B797A2A6B583; // 0x0008(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Index_5_1E7B0BAB4F0512C42C44508E9FEC776A;          // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CurrentRandomDeviation_11_9C78B0DB45A127EC7A77EEB883E56CBE; // 0x0028(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FBPS_Tesla_UnstableCoil_Target;

}

