#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ObjectiveTracker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_ObjectiveTracker.Widget_ObjectiveTracker_C
// 0x0030 (0x0370 - 0x0340)
class UWidget_ObjectiveTracker_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UListView*                              ListView_64;                                       // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Outro_Animation;                                   // 0x0350(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro_Animation;                                   // 0x0358(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TArray<class URGObjectiveScript*>             NewVar;                                            // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void AddNewEntry(class UObject* EntryObject);
	void Construct();
	void CREATEDELEGATE_PROXYFUNCTION_0(const struct FGameplayTag& ObjectiveTag, const class FText& UpdateInfo);
	void ExecuteUbergraph_Widget_ObjectiveTracker(int32 EntryPoint);
	void OnFinishRun_Event(bool RunFailed);
	void OnInitialized();
	void OnLevelChanged_Event();
	void OnObjectiveEnded(const struct FGameplayTag& ObjectiveTag, bool bCompleted);
	void OnObjectiveRemoved(const struct FGameplayTag& ObjectiveTag);
	void OnObjectiveStarted(class URGObjectiveScript* ObjectiveScript);
	void OnObjectiveUpdated(const struct FGameplayTag& ObjectiveTag, const class FText& UpdateInfo);
	void OnPlayerPawnKilled_Event(class ARPlayerPawn* Player);
	void PreConstruct(bool IsDesignTime);
	void SetupLevelChange();
	void UpdateVisibility();
	void UpdateVisibilityClient();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_ObjectiveTracker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_ObjectiveTracker_C")
	}
	static class UWidget_ObjectiveTracker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_ObjectiveTracker_C>();
	}
};
DUMPER7_ASSERTS_UWidget_ObjectiveTracker_C;

}

