#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ConsoleGraphicSettings

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Widget_SettingTabBase_classes.hpp"
#include "RGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_ConsoleGraphicSettings.Widget_ConsoleGraphicSettings_C
// 0x0028 (0x0370 - 0x0348)
class UWidget_ConsoleGraphicSettings_C final : public UWidget_SettingTabBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Widget_ConsoleGraphicSettings_C;    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UScrollBox*                             ScrollBox_0;                                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidget_SettingsCheckbox_C*             MotionBlur;                                        // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             GeneralTextBlock;                                  // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidget_SettingsCheckbox_C*             DepthOfField;                                      // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ApplySettings();
	void BndEvt__Widget_GraphicSettings_DepthOfField_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature(bool State);
	void BndEvt__Widget_GraphicSettings_MotionBlur_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature(bool State);
	void BP_GetScrollBoxWidget(class UScrollBox** Result);
	void Construct();
	void ExecuteUbergraph_Widget_ConsoleGraphicSettings(int32 EntryPoint);
	void GetFocusedWidget(class UUserWidget** FocusedWidget);
	void NextWidgetSettingsValue(class UUserWidget* Widget);
	void OnNavigationLeft();
	void OnNavigationRight();
	void PreviousWidgetSettingsValue(class UUserWidget* Widget);
	void ResetSettings();
	void SetupExplicitNavigations();
	void SetWidgetCurrentValues(bool bInit);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_ConsoleGraphicSettings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_ConsoleGraphicSettings_C")
	}
	static class UWidget_ConsoleGraphicSettings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_ConsoleGraphicSettings_C>();
	}
};
DUMPER7_ASSERTS_UWidget_ConsoleGraphicSettings_C;

}

