#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ArtifactUpgradeSelectScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Widget_LootSelectScreenBase_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_ArtifactUpgradeSelectScreen.Widget_ArtifactUpgradeSelectScreen_C
// 0x0048 (0x0590 - 0x0548)
class UWidget_ArtifactUpgradeSelectScreen_C final : public UWidget_LootSelectScreenBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Widget_ArtifactUpgradeSelectScreen_C; // 0x0548(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_Button_SimpleText_C*                 W_Button_SimpleText;                               // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Vignette;                                          // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SubheaderText;                                     // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           OptionContainer;                                   // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Header;                                            // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    CommonActionWidget_81;                             // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       ConstructAnimation;                                // 0x0580(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       TextFadeInAnimation;                               // 0x0588(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__Widget_AbilitySelectScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void Construct();
	void ExecuteUbergraph_Widget_ArtifactUpgradeSelectScreen(int32 EntryPoint);
	void Finished_44A434EB46D3B5E477B7DA94A49A00D3();
	void Initialize(TArray<struct FRLootSelectionOption>& LootOptions_0, const struct FGameplayTag& LootSelectionType_0, class ARPickupableItem* PickupableItem, EOrientation OptionOrientation);
	void OnLooted(const struct FRLootSelectionOption& LootSelectionOption);
	void ShowLootOptions();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_ArtifactUpgradeSelectScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_ArtifactUpgradeSelectScreen_C")
	}
	static class UWidget_ArtifactUpgradeSelectScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_ArtifactUpgradeSelectScreen_C>();
	}
};
DUMPER7_ASSERTS_UWidget_ArtifactUpgradeSelectScreen_C;

}

