#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_PlayerGameOverScreen

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "RGame_structs.hpp"
#include "CommonInput_structs.hpp"


namespace SDK::Params
{

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_1_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Left_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Left_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Left_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Right_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Right_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_BndEvt__Widget_PlayerGameOverScreen_W_PageButton_Right_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.ConstructButtons
// 0x0010 (0x0010 - 0x0000)
struct Widget_PlayerGameOverScreen_C_ConstructButtons final
{
public:
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_ConstructButtons;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.ExecuteUbergraph_Widget_PlayerGameOverScreen
// 0x00C0 (0x00C0 - 0x0000)
struct Widget_PlayerGameOverScreen_C_ExecuteUbergraph_Widget_PlayerGameOverScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARPlayerState*                          K2Node_DynamicCast_AsRPlayer_State;                // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARAssetLoader*                          CallFunc_GetAssetLoader_ReturnValue;               // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsNotEmpty_ReturnValue;             // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_1;            // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARPlayerState*                          K2Node_DynamicCast_AsRPlayer_State_1;              // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_3;               // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_2;            // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget_ChallengesCompletedPopup_C*     CallFunc_PushWidget_OutWidget;                     // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue_3;            // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARGamePlayerController*                 K2Node_DynamicCast_AsRGame_Player_Controller;      // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSingleplayer_Value;                     // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9B[0x1];                                       // 0x009B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UWidget_PlayerGameOverPlayerTile_C* SelectedPlayerTile)> K2Node_CreateDelegate_OutputDelegate; // 0x009C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_GetVisibility_ReturnValue;                // 0x00AE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              CallFunc_GetVisibility_ReturnValue_1;              // 0x00AF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate_1;          // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_ExecuteUbergraph_Widget_PlayerGameOverScreen;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.HandleSelectPlayerTile
// 0x0178 (0x0178 - 0x0000)
struct Widget_PlayerGameOverScreen_C_HandleSelectPlayerTile final
{
public:
	class UWidget_PlayerGameOverPlayerTile_C*     SelectedPlayerTile;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ARPlayerState*                          CallFunc_GetSelectedPlayerState_RPlayerState;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRPlayerStats                          CallFunc_GetSelectedStats_RPlayerStats;            // 0x0010(0x0128)()
	class APawn*                                  CallFunc_GetPawn_ReturnValue;                      // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARPlayerPawn*                           K2Node_DynamicCast_AsRPlayer_Pawn;                 // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x014C(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget_TabMenuEntry_C*                 CallFunc_Create_ReturnValue;                       // 0x0168(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0170(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_HandleSelectPlayerTile;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.OnInputMethodChanged_Event
// 0x0001 (0x0001 - 0x0000)
struct Widget_PlayerGameOverScreen_C_OnInputMethodChanged_Event final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_OnInputMethodChanged_Event;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.SavePlayerStats
// 0x0018 (0x0018 - 0x0000)
struct Widget_PlayerGameOverScreen_C_SavePlayerStats final
{
public:
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARPlayerState*                          K2Node_DynamicCast_AsRPlayer_State;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_SavePlayerStats;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.SetTitleText
// 0x0010 (0x0010 - 0x0000)
struct Widget_PlayerGameOverScreen_C_SetTitleText final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_SetTitleText;

// Function Widget_PlayerGameOverScreen.Widget_PlayerGameOverScreen_C.BP_GetDesiredFocusTarget
// 0x0020 (0x0020 - 0x0000)
struct Widget_PlayerGameOverScreen_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_TabMenuEntry_C*                 K2Node_DynamicCast_AsWidget_Tab_Menu_Entry;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_PlayerGameOverScreen_C_BP_GetDesiredFocusTarget;

}

