#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_SettingsButtonBase

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_SettingsButtonBase.Widget_SettingsButtonBase_C
// 0x0018 (0x0358 - 0x0340)
class UWidget_SettingsButtonBase_C final : public UUserWidget
{
public:
	class UTextBlock*                             Setting;                                           // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   SettingName;                                       // 0x0348(0x0010)(Edit, BlueprintVisible)

public:
	void Set_Setting_Name(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_SettingsButtonBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_SettingsButtonBase_C")
	}
	static class UWidget_SettingsButtonBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_SettingsButtonBase_C>();
	}
};
DUMPER7_ASSERTS_UWidget_SettingsButtonBase_C;

}

