#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_PlayerDeathScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RGame_classes.hpp"
#include "CommonInput_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Widget_PlayerDeathScreen.Widget_PlayerDeathScreen_C
// 0x0048 (0x0508 - 0x04C0)
class UWidget_PlayerDeathScreen_C final : public URCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_Button_SimpleText_C*                 W_Button_SimpleText;                               // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             SlainByText;                                       // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SkullImage;                                        // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             FatalBlowDamageText;                               // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    CommonActionWidget_73;                             // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Start_Animation;                                   // 0x04F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class ARPlayerPawn*                           RPlayer_Pawn;                                      // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBPCM_PlayerDeathEffect_C*              CameraModifier;                                    // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AddCameraModifier();
	void BndEvt__Widget_PlayerDeathScreen_W_Button_SimpleText_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void Construct();
	void ExecuteUbergraph_Widget_PlayerDeathScreen(int32 EntryPoint);
	void OnInitialized();
	void OnInputMethodChanged(ECommonInputType bNewInputType);
	void OnLevelChanged();
	void OnPlayerRespawn(class ARPlayerPawn* Player);
	void StartAnimationFinished();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Widget_PlayerDeathScreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Widget_PlayerDeathScreen_C")
	}
	static class UWidget_PlayerDeathScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWidget_PlayerDeathScreen_C>();
	}
};
DUMPER7_ASSERTS_UWidget_PlayerDeathScreen_C;

}

