#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_GraphicSettings

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_AA_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_AA_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_AA_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_AAQuality_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_AAQuality_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_AAQuality_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_ButtonAutomaticQuality_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_ButtonAutomaticQuality_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_ButtonAutomaticQuality_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_DepthOfField_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_DepthOfField_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_DepthOfField_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_EnvDetail_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_EnvDetail_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_EnvDetail_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_GI_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_GI_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_GI_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_MotionBlur_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_MotionBlur_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_MotionBlur_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_Overall_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_Overall_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_Overall_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_PostProcessQuality_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_PostProcessQuality_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_PostProcessQuality_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_Shadows_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_Shadows_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_Shadows_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_TextDetail_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_TextDetail_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_TextDetail_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_TSRSharpness_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_TSRSharpness_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature final
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Percent;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_TSRSharpness_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BndEvt__Widget_GraphicSettings_VisualEffects_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_VisualEffects_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BndEvt__Widget_GraphicSettings_VisualEffects_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.BP_GetScrollBoxWidget
// 0x0008 (0x0008 - 0x0000)
struct Widget_GraphicSettings_C_BP_GetScrollBoxWidget final
{
public:
	class UScrollBox*                             Result;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_BP_GetScrollBoxWidget;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.ExecuteUbergraph_Widget_GraphicSettings
// 0x0148 (0x0148 - 0x0000)
struct Widget_GraphicSettings_C_ExecuteUbergraph_Widget_GraphicSettings final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_1;       // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_2;       // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_3;       // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_4;       // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_5;       // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_GetFocusedWidget_FocusedWidget;           // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_GetFocusedWidget_FocusedWidget_1;         // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_8;                // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_6;       // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_7;       // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDepthOfFieldEnabled_ReturnValue;       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetResolutionScaleInformationEx_CurrentScaleNormalized; // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_CurrentScaleValue; // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_MinScaleValue; // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_MaxScaleValue; // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetGIType_ReturnValue;                    // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPostProcessingQuality_ReturnValue;     // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetTextureQuality_ReturnValue;            // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFoliageQuality_ReturnValue;            // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetVisualEffectQuality_ReturnValue;       // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetAntiAliasingQuality_ReturnValue;       // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetAAType_ReturnValue;                    // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_8;       // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_7;                // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_6;                // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_9;       // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_ComponentBoundEvent_Value;                  // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_ComponentBoundEvent_Percent;                // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_10;      // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_11;      // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_State_1;                // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_12;      // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_State;                  // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_13;      // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x00FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue_14;      // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_5;                // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_4;                // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_3;                // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_2;                // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index_1;                // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Index;                  // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Select_Default_1;                           // 0x0134(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_135[0x3];                                      // 0x0135(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SetValue_InValue_ImplicitCast;            // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScreenPercentage_newValue_ImplicitCast; // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_ExecuteUbergraph_Widget_GraphicSettings;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.Get_TSRSharpness_Visibility
// 0x0018 (0x0018 - 0x0000)
struct Widget_GraphicSettings_C_Get_TSRSharpness_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetAAType_ReturnValue;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_Get_TSRSharpness_Visibility;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.GetFocusedWidget
// 0x0050 (0x0050 - 0x0000)
struct Widget_GraphicSettings_C_GetFocusedWidget final
{
public:
	class UUserWidget*                            FocusedWidget;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0018(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            K2Node_DynamicCast_AsUser_Widget;                  // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue;             // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_GetFocusedWidget;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.NextWidgetSettingsValue
// 0x0018 (0x0018 - 0x0000)
struct Widget_GraphicSettings_C_NextWidgetSettingsValue final
{
public:
	class UUserWidget*                            Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_SettingsOptions_C*              K2Node_DynamicCast_AsWidget_Settings_Options;      // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_NextWidgetSettingsValue;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.PreviousWidgetSettingsValue
// 0x0018 (0x0018 - 0x0000)
struct Widget_GraphicSettings_C_PreviousWidgetSettingsValue final
{
public:
	class UUserWidget*                            Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_SettingsOptions_C*              K2Node_DynamicCast_AsWidget_Settings_Options;      // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_PreviousWidgetSettingsValue;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.SetWidgetCurrentValues
// 0x0080 (0x0080 - 0x0000)
struct Widget_GraphicSettings_C_SetWidgetCurrentValues final
{
public:
	bool                                          bInit;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue;         // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetOverallScalabilityLevel_ReturnValue;   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDepthOfFieldEnabled_ReturnValue;       // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetMotionBlurEnabled_ReturnValue;         // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E[0x2];                                       // 0x002E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetResolutionScaleInformationEx_CurrentScaleNormalized; // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_CurrentScaleValue; // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_MinScaleValue; // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetResolutionScaleInformationEx_MaxScaleValue; // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScreenPercentage_ReturnValue;          // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetGIType_ReturnValue;                    // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPostProcessingQuality_ReturnValue;     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetTextureQuality_ReturnValue;            // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFoliageQuality_ReturnValue;            // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetVisualEffectQuality_ReturnValue;       // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetAntiAliasingQuality_ReturnValue;       // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetAAType_ReturnValue;                    // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_B_ImplicitCast;               // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_A_ImplicitCast;               // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_SetWidgetCurrentValues;

// Function Widget_GraphicSettings.Widget_GraphicSettings_C.UpdateOveralSettingWidget
// 0x0010 (0x0010 - 0x0000)
struct Widget_GraphicSettings_C_UpdateOveralSettingWidget final
{
public:
	class URGameUserSettings*                     CallFunc_GetRGameUserSettings_ReturnValue;         // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetOverallScalabilityLevel_ReturnValue;   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_GraphicSettings_C_UpdateOveralSettingWidget;

}

