#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_ConfirmPrompt

#include "Basic.hpp"


namespace SDK::Params
{

// Function Widget_ConfirmPrompt.Widget_ConfirmPrompt_C.BndEvt__Widget_ConfirmPrompt_W_Button_No_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_ConfirmPrompt_C_BndEvt__Widget_ConfirmPrompt_W_Button_No_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_ConfirmPrompt_C_BndEvt__Widget_ConfirmPrompt_W_Button_No_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_ConfirmPrompt.Widget_ConfirmPrompt_C.BndEvt__Widget_ConfirmPrompt_W_Button_Yes_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_ConfirmPrompt_C_BndEvt__Widget_ConfirmPrompt_W_Button_Yes_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_ConfirmPrompt_C_BndEvt__Widget_ConfirmPrompt_W_Button_Yes_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature;

// Function Widget_ConfirmPrompt.Widget_ConfirmPrompt_C.ExecuteUbergraph_Widget_ConfirmPrompt
// 0x0018 (0x0018 - 0x0000)
struct Widget_ConfirmPrompt_C_ExecuteUbergraph_Widget_ConfirmPrompt final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_ConfirmPrompt_C_ExecuteUbergraph_Widget_ConfirmPrompt;

// Function Widget_ConfirmPrompt.Widget_ConfirmPrompt_C.Initialize
// 0x0040 (0x0040 - 0x0000)
struct Widget_ConfirmPrompt_C_Initialize final
{
public:
	class FText                                   PromptText_0;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   PromptHeader_0;                                    // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   PromptYesText_0;                                   // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   PromptNoText_0;                                    // 0x0030(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Widget_ConfirmPrompt_C_Initialize;

// Function Widget_ConfirmPrompt.Widget_ConfirmPrompt_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct Widget_ConfirmPrompt_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_ConfirmPrompt_C_PreConstruct;

}

