#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_SkipCinematic

#include "Basic.hpp"

#include "Widget_SkipCinematic_classes.hpp"
#include "Widget_SkipCinematic_parameters.hpp"


namespace SDK
{

// Function Widget_SkipCinematic.Widget_SkipCinematic_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_SkipCinematic_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.ExecuteUbergraph_Widget_SkipCinematic
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_SkipCinematic_C::ExecuteUbergraph_Widget_SkipCinematic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "ExecuteUbergraph_Widget_SkipCinematic");

	Params::Widget_SkipCinematic_C_ExecuteUbergraph_Widget_SkipCinematic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.GetHoldActionKeyMapping
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FEnhancedActionKeyMapping*       Mapping                                                (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)

void UWidget_SkipCinematic_C::GetHoldActionKeyMapping(struct FEnhancedActionKeyMapping* Mapping)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "GetHoldActionKeyMapping");

	Params::Widget_SkipCinematic_C_GetHoldActionKeyMapping Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Mapping != nullptr)
		*Mapping = std::move(Parms.Mapping);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_SkipCinematic_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.OnKeyUp
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWidget_SkipCinematic_C::OnKeyUp(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "OnKeyUp");

	Params::Widget_SkipCinematic_C_OnKeyUp Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.OnPreviewKeyDown
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWidget_SkipCinematic_C::OnPreviewKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "OnPreviewKeyDown");

	Params::Widget_SkipCinematic_C_OnPreviewKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.SkipCinematic
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWidget_SkipCinematic_C::SkipCinematic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "SkipCinematic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_SkipCinematic_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "Tick");

	Params::Widget_SkipCinematic_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.UpdateKeyboardHelper
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_SkipCinematic_C::UpdateKeyboardHelper(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "UpdateKeyboardHelper");

	Params::Widget_SkipCinematic_C_UpdateKeyboardHelper Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_SkipCinematic.Widget_SkipCinematic_C.UpdateNumPlayersSkippedCinematic
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             NumPlayersSkipped                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_SkipCinematic_C::UpdateNumPlayersSkippedCinematic(const int32 NumPlayersSkipped)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_SkipCinematic_C", "UpdateNumPlayersSkippedCinematic");

	Params::Widget_SkipCinematic_C_UpdateNumPlayersSkippedCinematic Parms{};

	Parms.NumPlayersSkipped = NumPlayersSkipped;

	UObject::ProcessEvent(Func, &Parms);
}

}

