#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_Regular_Crosshair

#include "Basic.hpp"

#include "Widget_Regular_Crosshair_classes.hpp"
#include "Widget_Regular_Crosshair_parameters.hpp"


namespace SDK
{

// Function Widget_Regular_Crosshair.Widget_Regular_Crosshair_C.ExecuteUbergraph_Widget_Regular_Crosshair
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_Regular_Crosshair_C::ExecuteUbergraph_Widget_Regular_Crosshair(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_Regular_Crosshair_C", "ExecuteUbergraph_Widget_Regular_Crosshair");

	Params::Widget_Regular_Crosshair_C_ExecuteUbergraph_Widget_Regular_Crosshair Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_Regular_Crosshair.Widget_Regular_Crosshair_C.OnCrosshairColorChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              NewColor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWidget_Regular_Crosshair_C::OnCrosshairColorChanged(const struct FLinearColor& NewColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_Regular_Crosshair_C", "OnCrosshairColorChanged");

	Params::Widget_Regular_Crosshair_C_OnCrosshairColorChanged Parms{};

	Parms.NewColor = std::move(NewColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Widget_Regular_Crosshair.Widget_Regular_Crosshair_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWidget_Regular_Crosshair_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Widget_Regular_Crosshair_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

