#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Widget_CommonInviteMenu

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonInviteMenu_C_BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature final
{
public:
	class UWidget_TextButton_C*                   Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BndEvt__Widget_CommonInviteMenu_InviteFriendsButton_K2Node_ComponentBoundEvent_9_OnPressed__DelegateSignature;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature final
{
public:
	class UWidget_TextButton_C*                   Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionBrowserButton_K2Node_ComponentBoundEvent_4_OnPressed__DelegateSignature;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature final
{
public:
	class UWidget_TextButton_C*                   Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BndEvt__Widget_CommonPauseMenu_SessionSettingsButton_K2Node_ComponentBoundEvent_5_OnPressed__DelegateSignature;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct Widget_CommonInviteMenu_C_BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature final
{
public:
	class UWidget_TextButton_C*                   Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BndEvt__Widget_PauseMenu_ExitButton_K2Node_ComponentBoundEvent_6_OnPressed__DelegateSignature;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BP_OnHandleBackAction
// 0x0001 (0x0001 - 0x0000)
struct Widget_CommonInviteMenu_C_BP_OnHandleBackAction final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BP_OnHandleBackAction;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.ExecuteUbergraph_Widget_CommonInviteMenu
// 0x0048 (0x0048 - 0x0000)
struct Widget_CommonInviteMenu_C_ExecuteUbergraph_Widget_CommonInviteMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ESlateVisibility InVisibility)> K2Node_CreateDelegate_OutputDelegate;             // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimation_ReturnValue;                // 0x0014(0x0010)(NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_CustomEvent_InVisibility;                   // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget_TextButton_C*                   K2Node_ComponentBoundEvent_Button_3;               // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_TextButton_C*                   K2Node_ComponentBoundEvent_Button_2;               // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_TextButton_C*                   K2Node_ComponentBoundEvent_Button_1;               // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWidget_TextButton_C*                   K2Node_ComponentBoundEvent_Button;                 // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_ExecuteUbergraph_Widget_CommonInviteMenu;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.GetFocusedMenuButton
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonInviteMenu_C_GetFocusedMenuButton final
{
public:
	class UWidget_TextButton_C*                   Button;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue;             // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue_1;           // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue_2;           // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasKeyboardFocus_ReturnValue_3;           // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_GetFocusedMenuButton;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.OnVisibilityChanged_Event
// 0x0001 (0x0001 - 0x0000)
struct Widget_CommonInviteMenu_C_OnVisibilityChanged_Event final
{
public:
	ESlateVisibility                              InVisibility;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_OnVisibilityChanged_Event;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SessionBrowserPressed
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonInviteMenu_C_SessionBrowserPressed final
{
public:
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget_CommonSessionBrowser_C*         CallFunc_PushWidget_OutWidget;                     // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_SessionBrowserPressed;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SessionSettingsPressed
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonInviteMenu_C_SessionSettingsPressed final
{
public:
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidget_CommonUpdateSession_C*          CallFunc_PushWidget_OutWidget;                     // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_SessionSettingsPressed;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetSessionBrowserButtonVisibility
// 0x0018 (0x0018 - 0x0000)
struct Widget_CommonInviteMenu_C_SetSessionBrowserButtonVisibility final
{
public:
	class AROverworldManager*                     CallFunc_GetOverworldManager_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInLobby_ReturnValue;                    // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLoggedIn_ReturnValue;                   // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_SetSessionBrowserButtonVisibility;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetSessionSettingsButtonVisibility
// 0x0018 (0x0018 - 0x0000)
struct Widget_CommonInviteMenu_C_SetSessionSettingsButtonVisibility final
{
public:
	class AROverworldManager*                     CallFunc_GetOverworldManager_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSessionHost_ReturnValue;                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInLobby_ReturnValue;                    // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B[0x1];                                        // 0x000B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLoggedIn_ReturnValue;                   // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_SetSessionSettingsButtonVisibility;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.SetWidgetFocus
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonInviteMenu_C_SetWidgetFocus final
{
public:
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_SetWidgetFocus;

// Function Widget_CommonInviteMenu.Widget_CommonInviteMenu_C.BP_GetDesiredFocusTarget
// 0x0010 (0x0010 - 0x0000)
struct Widget_CommonInviteMenu_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Widget_CommonInviteMenu_C_BP_GetDesiredFocusTarget;

}

